### ISSUE TITLE
Dragpan is very jumpy in Safari.

### ISSUE THREAD

**Issue by crowtherdr** [lgoldstien/jquery-dragpan#14]
Dragging in Safari (Mac at least versions 7 & 8), the dragging is very jumpy and seems to resist being dragged.

**Comment by lgoldstien** [comment]
Hi @crowtherdr, I've been extremely busy so far this year so haven't had much of a chance to do anything open source. I've sorted #13 and had a little look at this one. Can you provide a little more information on the situation?

I've tested in Safari on Yosemite (whatever the latest version is, I don't use Safari) and haven't found any issues with dragging. Can you give it a quick test against http://lgoldstien.github.io/jquery-dragpan/ to see if the standard text div scrolling is affected?

Cheers.

**Comment by crowtherdr** [comment]
I understand about being busy. Thanks for the response. I tried http://lgoldstien.github.io/jquery-dragpan/ in Safari and it was not jumpy.
